import type {
  AgentRunStepView,
  AgentRunView,
  ClarificationView,
  PlanGraphView,
  ProjectView,
  SessionView,
} from "../api/types";

export const ids = {
  user: "d070c7d4-e602-45cc-afb0-e83ccac65465",
  project: "10000000-0000-4000-8000-000000000001",
  run: "20000000-0000-4000-8000-000000000001",
  plan: "30000000-0000-4000-8000-000000000001",
  analysis: "40000000-0000-4000-8000-000000000001",
  milestone1: "50000000-0000-4000-8000-000000000001",
  milestone2: "50000000-0000-4000-8000-000000000002",
  task1: "60000000-0000-4000-8000-000000000001",
  task2: "60000000-0000-4000-8000-000000000002",
  dependency: "70000000-0000-4000-8000-000000000001",
  question: "80000000-0000-4000-8000-000000000001",
};

export const sessionFixture: SessionView = {
  user: { id: ids.user, email: "owner@example.com", status: "active" },
  expires_at: "2026-07-29T12:00:00Z",
  csrf_token: null,
};

export const projectFixture: ProjectView = {
  id: ids.project,
  name: "Campus Services Portal",
  goal: "Deliver an accessible portal for university service requests.",
  desired_outcome: "Students can submit and track requests.",
  start_date: "2026-08-03",
  deadline: "2026-10-30",
  timezone: "Africa/Cairo",
  capacity_hours_per_week: "40",
  team_size: 3,
  status: "active",
  notes: null,
  row_version: 1,
  created_at: "2026-07-23T10:00:00Z",
  updated_at: "2026-07-23T10:00:00Z",
  requirements: [
    {
      id: "90000000-0000-4000-8000-000000000001",
      kind: "stated",
      text: "Students submit service requests",
      source: "user",
      status: "confirmed",
      created_at: "2026-07-23T10:00:00Z",
    },
  ],
  constraints: [],
  calendars: [],
};

export const runFixture: AgentRunView = {
  id: ids.run,
  project_id: ids.project,
  workflow: "planning",
  status: "waiting_for_user",
  current_step: "wait_or_assume",
  token_budget: 50_000,
  tokens_used: 1_240,
  cancel_requested: false,
  proposed_plan_version_id: null,
  outcome: null,
  created_at: "2026-07-23T10:01:00Z",
  updated_at: "2026-07-23T10:02:00Z",
  started_at: "2026-07-23T10:01:01Z",
  completed_at: null,
};

export const runStepsFixture: AgentRunStepView[] = [
  {
    id: "a0000000-0000-4000-8000-000000000001",
    name: "validate_request",
    mode: "deterministic",
    purpose: "Internal purpose not rendered",
    attempt: 1,
    status: "completed",
    input_refs: [],
    output_refs: [],
    validation: [],
    usage: {},
    failure_code: null,
    retryable: false,
    started_at: "2026-07-23T10:01:01Z",
    completed_at: "2026-07-23T10:01:02Z",
    duration_ms: 1_000,
  },
  {
    id: "a0000000-0000-4000-8000-000000000002",
    name: "wait_or_assume",
    mode: "human",
    purpose: "Internal purpose not rendered",
    attempt: 1,
    status: "waiting",
    input_refs: [],
    output_refs: [],
    validation: [],
    usage: {},
    failure_code: null,
    retryable: false,
    started_at: "2026-07-23T10:02:00Z",
    completed_at: null,
    duration_ms: null,
  },
];

export const clarificationFixture: ClarificationView = {
  id: ids.question,
  run_id: ids.run,
  stable_key: "Q-001",
  question: "Which service category must launch first?",
  reason: "The first release needs a clear scope boundary.",
  affects: ["MOD-001", "MS-001"],
  required: true,
  answer_type: "single_choice",
  options: ["Facilities", "IT support"],
  default_assumption: "Facilities",
  source_fact_refs: ["REQ-001"],
  answer_json: null,
  status: "open",
  created_at: "2026-07-23T10:02:00Z",
  updated_at: "2026-07-23T10:02:00Z",
};

export const planFixture: PlanGraphView = {
  id: ids.plan,
  project_id: ids.project,
  number: 1,
  state: "draft",
  based_on_id: null,
  reason: "Initial generated project plan",
  content_hash: `sha256:${"a".repeat(64)}`,
  quality_status: "passed",
  row_version: 7,
  created_at: "2026-07-23T10:10:00Z",
  updated_at: "2026-07-23T10:10:00Z",
  quality_report: { passed: true, issues: [] },
  analysis: {
    id: ids.analysis,
    version_id: ids.plan,
    summary: "The portal needs a focused service-request workflow with accessible status tracking.",
    project_type: "web_application",
    intended_users: ["Students", "Service staff"],
    objectives: [{ ref: "OBJ-001", statement: "Submit a request" }],
    success_criteria: [{ ref: "SC-001", statement: "Request persists" }],
    modules: [
      {
        temp_id: "MOD-001",
        name: "Request intake",
        description: "Collect and validate service requests.",
      },
    ],
    workstreams: ["Frontend", "Backend"],
    assumptions: [{ temp_id: "ASM-001", statement: "University identity is available." }],
    constraints: [],
    complexity: "medium",
    mvp_boundary: ["Create and track requests"],
    excluded_scope: ["Portfolio reporting"],
  },
  milestones: [
    {
      id: ids.milestone1,
      version_id: ids.plan,
      stable_key: "MS-001",
      module_refs: ["MOD-001"],
      name: "Request intake ready",
      description: "Deliver the validated request intake workflow for student services.",
      objective: "Let students submit complete service requests.",
      deliverable: "Accessible service request form",
      sequence: 1,
      target_date: "2026-08-21",
      planned_effort_hours: "20",
      acceptance_criteria: ["A valid request persists"],
      planned_start: "2026-08-03",
      planned_finish: "2026-08-07",
      status: "pending",
      source: "ai",
      protected: false,
      locked: false,
      row_version: 1,
    },
    {
      id: ids.milestone2,
      version_id: ids.plan,
      stable_key: "MS-002",
      module_refs: ["MOD-001"],
      name: "Status tracking ready",
      description: "Deliver clear request status tracking for students and service staff.",
      objective: "Make service request progress visible.",
      deliverable: "Request status timeline",
      sequence: 2,
      target_date: "2026-08-28",
      planned_effort_hours: "12",
      acceptance_criteria: ["Every status has text and timestamp"],
      planned_start: "2026-08-10",
      planned_finish: "2026-08-12",
      status: "pending",
      source: "user",
      protected: true,
      locked: false,
      row_version: 1,
    },
  ],
  tasks: [
    {
      id: ids.task1,
      version_id: ids.plan,
      milestone_id: ids.milestone1,
      parent_id: null,
      stable_key: "TASK-001",
      title: "Build request form",
      description: "Implement the accessible service request form and server validation.",
      deliverable: "Validated request form",
      acceptance_criteria: ["Invalid requests show field errors"],
      definition_of_done: ["Component and API tests pass"],
      effort_min_hours: "8",
      effort_likely_hours: "12",
      effort_max_hours: "16",
      complexity: "medium",
      workstreams: ["Frontend", "Backend"],
      skill_tags: ["React", "FastAPI"],
      source: "ai",
      requirement_refs: ["REQ-001"],
      assumption_refs: [],
      locked: false,
      protected: false,
      priority_score: "82.5",
      priority_label: "High",
      priority_breakdown: {
        mvp_necessity: 100,
        deadline_urgency: 60,
        user_value: 90,
        risk_reduction: 40,
        user_preference: 50,
      },
      planned_start: "2026-08-03",
      planned_finish: "2026-08-04",
      status: "pending",
      row_version: 1,
    },
    {
      id: ids.task2,
      version_id: ids.plan,
      milestone_id: ids.milestone2,
      parent_id: null,
      stable_key: "TASK-002",
      title: "Render request status",
      description: "Render the persisted request history as an accessible status timeline.",
      deliverable: "Accessible request timeline",
      acceptance_criteria: ["Status is not conveyed by color alone"],
      definition_of_done: ["Keyboard and axe checks pass"],
      effort_min_hours: "4",
      effort_likely_hours: "8",
      effort_max_hours: "12",
      complexity: "low",
      workstreams: ["Frontend"],
      skill_tags: ["React"],
      source: "user",
      requirement_refs: ["REQ-001"],
      assumption_refs: [],
      locked: false,
      protected: true,
      priority_score: "70",
      priority_label: "Medium",
      priority_breakdown: {
        mvp_necessity: 80,
        deadline_urgency: 50,
        user_value: 80,
        risk_reduction: 30,
        user_preference: 50,
      },
      planned_start: "2026-08-10",
      planned_finish: "2026-08-10",
      status: "pending",
      row_version: 1,
    },
  ],
  dependencies: [
    {
      id: ids.dependency,
      version_id: ids.plan,
      predecessor_id: ids.task1,
      successor_id: ids.task2,
      dependency_type: "finish_to_start",
      reason: "A request must exist before its status can be displayed.",
      evidence_refs: ["TASK-001", "TASK-002"],
      confidence_label: "high",
      source: "ai",
      protected: false,
    },
  ],
  risks: [
    {
      temp_id: "RISK-001",
      title: "Identity provider availability",
      mitigation: "Validate the identity contract before implementation.",
    },
  ],
  approvals: [],
};
