"""Create persistent planning workflow schema.

Revision ID: 0005_planning_workflow
Revises: 0004_ai_contracts
Create Date: 2026-07-23 17:43:50.955226
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql.sqltypes import Text

revision: str = "0005_planning_workflow"
down_revision: str | None = "0004_ai_contracts"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("initiator_id", sa.Uuid(), nullable=False),
        sa.Column("workflow", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("input_hash", sa.String(length=71), nullable=False),
        sa.Column("token_budget", sa.Integer(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("current_step", sa.String(length=80), nullable=False),
        sa.Column(
            "state_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "candidate_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("proposed_plan_version_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'waiting_for_user', 'partial', "
            "'failed', 'completed', 'cancelled')",
            name=op.f("ck_agent_runs_status_allowed"),
        ),
        sa.CheckConstraint("workflow IN ('planning')", name=op.f("ck_agent_runs_workflow_allowed")),
        sa.CheckConstraint("token_budget > 0", name=op.f("ck_agent_runs_token_budget_positive")),
        sa.CheckConstraint("tokens_used >= 0", name=op.f("ck_agent_runs_tokens_used_nonnegative")),
        sa.ForeignKeyConstraint(
            ["initiator_id"],
            ["users.id"],
            name=op.f("fk_agent_runs_initiator_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_agent_runs_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
        sa.UniqueConstraint(
            "initiator_id", "idempotency_key", name="agent_run_initiator_idempotency"
        ),
    )
    op.create_index(
        "ix_agent_runs_project_status_created",
        "agent_runs",
        ["project_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "plan_versions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("based_on_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("content_hash", sa.String(length=71), nullable=False),
        sa.Column("quality_status", sa.String(length=16), nullable=False),
        sa.Column(
            "quality_report",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source_run_id", sa.Uuid(), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "quality_status IN ('passed', 'failed')",
            name=op.f("ck_plan_versions_quality_status_allowed"),
        ),
        sa.CheckConstraint(
            "state IN ('idea', 'clarification_required', 'generating', 'draft', "
            "'under_review', 'approved', 'active', 'archived', 'superseded')",
            name=op.f("ck_plan_versions_state_allowed"),
        ),
        sa.CheckConstraint("number >= 1", name=op.f("ck_plan_versions_number_positive")),
        sa.CheckConstraint("row_version >= 1", name=op.f("ck_plan_versions_row_version_positive")),
        sa.ForeignKeyConstraint(
            ["based_on_id"],
            ["plan_versions.id"],
            name=op.f("fk_plan_versions_based_on_id_plan_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_plan_versions_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_versions")),
        sa.UniqueConstraint("project_id", "number", name="plan_version_project_number"),
        sa.UniqueConstraint("source_run_id", name="plan_version_source_run"),
    )
    op.create_index(
        "ix_plan_versions_project_state_created",
        "plan_versions",
        ["project_id", "state", "created_at"],
        unique=False,
    )
    op.create_table(
        "agent_jobs",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column(
            "payload_ref",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_by", sa.String(length=120), nullable=True),
        sa.Column("claim_token", sa.Uuid(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=80), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("job_type IN ('planning')", name=op.f("ck_agent_jobs_job_type_allowed")),
        sa.CheckConstraint(
            "status IN ('queued', 'claimed', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_agent_jobs_status_allowed"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_agent_jobs_attempts_nonnegative")),
        sa.CheckConstraint("max_attempts >= 1", name=op.f("ck_agent_jobs_max_attempts_positive")),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_agent_jobs_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_jobs")),
        sa.UniqueConstraint("idempotency_key", name="agent_job_idempotency"),
    )
    op.create_index(
        "ix_agent_jobs_claim",
        "agent_jobs",
        ["status", "available_at", "lease_expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_agent_jobs_run_created", "agent_jobs", ["run_id", "created_at"], unique=False
    )
    op.create_table(
        "agent_run_steps",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("purpose", sa.String(length=500), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("input_hash", sa.String(length=71), nullable=False),
        sa.Column("idempotency_key", sa.String(length=240), nullable=False),
        sa.Column(
            "input_refs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "output_refs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "validation",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "usage",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("failure_code", sa.String(length=80), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "mode IN ('deterministic', 'llm', 'human', 'transactional')",
            name=op.f("ck_agent_run_steps_mode_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed', 'cancelled', 'skipped')",
            name=op.f("ck_agent_run_steps_status_allowed"),
        ),
        sa.CheckConstraint("attempt >= 1", name=op.f("ck_agent_run_steps_attempt_positive")),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0",
            name=op.f("ck_agent_run_steps_duration_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_agent_run_steps_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_run_steps")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_agent_run_steps_idempotency_key")),
        sa.UniqueConstraint("run_id", "name", "attempt", name="agent_run_step_attempt"),
    )
    op.create_index(
        "ix_agent_run_steps_input",
        "agent_run_steps",
        ["run_id", "name", "input_hash", "status"],
        unique=False,
    )
    op.create_index(
        "ix_agent_run_steps_run_started", "agent_run_steps", ["run_id", "started_at"], unique=False
    )
    op.create_table(
        "clarification_questions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=20), nullable=False),
        sa.Column("source_temp_id", sa.String(length=20), nullable=False),
        sa.Column("question", sa.String(length=500), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "affects",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("answer_type", sa.String(length=24), nullable=False),
        sa.Column(
            "options",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("default_assumption", sa.String(length=500), nullable=True),
        sa.Column(
            "source_fact_refs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "answer_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("answered_by_id", sa.Uuid(), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "answer_type IN ('text', 'single_choice', 'multi_choice', 'boolean', 'date', 'number')",
            name=op.f("ck_clarification_questions_answer_type_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'answered', 'assumed', 'dismissed')",
            name=op.f("ck_clarification_questions_status_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["answered_by_id"],
            ["users.id"],
            name=op.f("fk_clarification_questions_answered_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_clarification_questions_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_clarification_questions_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clarification_questions")),
        sa.UniqueConstraint("project_id", "stable_key", name="clarification_project_key"),
        sa.UniqueConstraint("run_id", "source_temp_id", name="clarification_run_source"),
    )
    op.create_index(
        "ix_clarifications_project_status",
        "clarification_questions",
        ["project_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_clarifications_run_created",
        "clarification_questions",
        ["run_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "milestones",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=20), nullable=False),
        sa.Column(
            "module_refs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("objective", sa.String(length=500), nullable=False),
        sa.Column("deliverable", sa.String(length=500), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("planned_effort_hours", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "acceptance_criteria",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("planned_start", sa.Date(), nullable=True),
        sa.Column("planned_finish", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'in_progress', 'completed', 'cancelled')",
            name=op.f("ck_milestones_status_allowed"),
        ),
        sa.CheckConstraint("planned_effort_hours > 0", name=op.f("ck_milestones_effort_positive")),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_milestones_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["plan_versions.id"],
            name=op.f("fk_milestones_version_id_plan_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_milestones")),
        sa.UniqueConstraint("id", "version_id", name="milestone_id_version"),
        sa.UniqueConstraint("version_id", "sequence", name="milestone_version_sequence"),
        sa.UniqueConstraint("version_id", "stable_key", name="milestone_version_key"),
    )
    op.create_index(
        "ix_milestones_version_sequence", "milestones", ["version_id", "sequence"], unique=False
    )
    op.create_table(
        "project_analyses",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("project_type", sa.String(length=80), nullable=False),
        sa.Column(
            "intended_users",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "objectives",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "success_criteria",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "modules",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "workstreams",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "assumptions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "constraints",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("complexity", sa.String(length=20), nullable=False),
        sa.Column(
            "mvp_boundary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "excluded_scope",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["plan_versions.id"],
            name=op.f("fk_project_analyses_version_id_plan_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_analyses")),
        sa.UniqueConstraint("version_id", name="project_analysis_version"),
    )
    op.create_table(
        "risks",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=24), nullable=False),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("probability", sa.String(length=16), nullable=False),
        sa.Column("impact", sa.String(length=16), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.String(length=500), nullable=False),
        sa.Column("mitigation", sa.String(length=1000), nullable=False),
        sa.Column("contingency", sa.String(length=1000), nullable=False),
        sa.Column(
            "related_refs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "source_fact_refs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "category IN ('technical', 'schedule', 'scope', 'dependency', "
            "'security', 'quality', 'external')",
            name=op.f("ck_risks_category_allowed"),
        ),
        sa.CheckConstraint(
            "impact IN ('low', 'medium', 'high', 'critical')", name=op.f("ck_risks_impact_allowed")
        ),
        sa.CheckConstraint(
            "probability IN ('unlikely', 'possible', 'likely')",
            name=op.f("ck_risks_probability_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'mitigated', 'closed')", name=op.f("ck_risks_status_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["plan_versions.id"],
            name=op.f("fk_risks_version_id_plan_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risks")),
        sa.UniqueConstraint("version_id", "stable_key", name="risk_version_key"),
    )
    op.create_index("ix_risks_version_status", "risks", ["version_id", "status"], unique=False)
    op.create_table(
        "planning_decisions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=24), nullable=False),
        sa.Column("decision_type", sa.String(length=20), nullable=False),
        sa.Column("text", sa.String(length=1000), nullable=False),
        sa.Column("rationale", sa.String(length=1000), nullable=False),
        sa.Column("source_question_id", sa.Uuid(), nullable=True),
        sa.Column(
            "source_fact_refs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision_type IN ('answer', 'assumption')",
            name=op.f("ck_planning_decisions_type_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_planning_decisions_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_planning_decisions_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_question_id"],
            ["clarification_questions.id"],
            name=op.f("fk_planning_decisions_source_question_id_clarification_questions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_planning_decisions")),
        sa.UniqueConstraint("project_id", "stable_key", name="planning_decision_project_key"),
    )
    op.create_index(
        "ix_planning_decisions_run_created",
        "planning_decisions",
        ["run_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "tasks",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("milestone_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("stable_key", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("deliverable", sa.String(length=500), nullable=False),
        sa.Column(
            "acceptance_criteria",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "definition_of_done",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("effort_min_hours", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("effort_likely_hours", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("effort_max_hours", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("complexity", sa.String(length=20), nullable=False),
        sa.Column(
            "workstreams",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "skill_tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column(
            "requirement_refs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "assumption_refs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("priority_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("priority_label", sa.String(length=16), nullable=False),
        sa.Column(
            "priority_breakdown",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("planned_start", sa.Date(), nullable=True),
        sa.Column("planned_finish", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "complexity IN ('trivial', 'low', 'medium', 'high')",
            name=op.f("ck_tasks_complexity_allowed"),
        ),
        sa.CheckConstraint("source IN ('ai', 'user')", name=op.f("ck_tasks_source_allowed")),
        sa.CheckConstraint(
            "status IN ('pending', 'ready', 'in_progress', 'blocked', 'completed', 'cancelled')",
            name=op.f("ck_tasks_status_allowed"),
        ),
        sa.CheckConstraint(
            "effort_min_hours > 0 AND effort_likely_hours >= effort_min_hours "
            "AND effort_max_hours >= effort_likely_hours",
            name=op.f("ck_tasks_effort_ordered"),
        ),
        sa.CheckConstraint(
            "priority_score >= 0 AND priority_score <= 100", name=op.f("ck_tasks_priority_range")
        ),
        sa.CheckConstraint("row_version >= 1", name=op.f("ck_tasks_row_version_positive")),
        sa.ForeignKeyConstraint(
            ["milestone_id", "version_id"],
            ["milestones.id", "milestones.version_id"],
            name="task_milestone_same_version",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id", "version_id"],
            ["tasks.id", "tasks.version_id"],
            name="task_parent_same_version",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["plan_versions.id"],
            name=op.f("fk_tasks_version_id_plan_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("id", "version_id", name="task_id_version"),
        sa.UniqueConstraint("version_id", "stable_key", name="task_version_key"),
    )
    op.create_index(
        "ix_tasks_version_milestone", "tasks", ["version_id", "milestone_id"], unique=False
    )
    op.create_index(
        "ix_tasks_version_status_priority",
        "tasks",
        ["version_id", "status", "priority_score"],
        unique=False,
    )
    op.create_table(
        "task_dependencies",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("predecessor_id", sa.Uuid(), nullable=False),
        sa.Column("successor_id", sa.Uuid(), nullable=False),
        sa.Column("dependency_type", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "evidence_refs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("confidence_label", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "dependency_type = 'finish_to_start'",
            name=op.f("ck_task_dependencies_type_finish_to_start"),
        ),
        sa.CheckConstraint(
            "predecessor_id <> successor_id", name=op.f("ck_task_dependencies_endpoints_distinct")
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_id", "version_id"],
            ["tasks.id", "tasks.version_id"],
            name="dependency_predecessor_same_version",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["successor_id", "version_id"],
            ["tasks.id", "tasks.version_id"],
            name="dependency_successor_same_version",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["plan_versions.id"],
            name=op.f("fk_task_dependencies_version_id_plan_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_dependencies")),
        sa.UniqueConstraint(
            "version_id", "predecessor_id", "successor_id", name="task_dependency_edge"
        ),
    )
    op.create_index(
        "ix_task_dependencies_version_successor",
        "task_dependencies",
        ["version_id", "successor_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_dependencies_version_successor", table_name="task_dependencies")
    op.drop_table("task_dependencies")
    op.drop_index("ix_tasks_version_status_priority", table_name="tasks")
    op.drop_index("ix_tasks_version_milestone", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_planning_decisions_run_created", table_name="planning_decisions")
    op.drop_table("planning_decisions")
    op.drop_index("ix_risks_version_status", table_name="risks")
    op.drop_table("risks")
    op.drop_table("project_analyses")
    op.drop_index("ix_milestones_version_sequence", table_name="milestones")
    op.drop_table("milestones")
    op.drop_index("ix_clarifications_run_created", table_name="clarification_questions")
    op.drop_index("ix_clarifications_project_status", table_name="clarification_questions")
    op.drop_table("clarification_questions")
    op.drop_index("ix_agent_run_steps_run_started", table_name="agent_run_steps")
    op.drop_index("ix_agent_run_steps_input", table_name="agent_run_steps")
    op.drop_table("agent_run_steps")
    op.drop_index("ix_agent_jobs_run_created", table_name="agent_jobs")
    op.drop_index("ix_agent_jobs_claim", table_name="agent_jobs")
    op.drop_table("agent_jobs")
    op.drop_index("ix_plan_versions_project_state_created", table_name="plan_versions")
    op.drop_table("plan_versions")
    op.drop_index("ix_agent_runs_project_status_created", table_name="agent_runs")
    op.drop_table("agent_runs")
    # ### end Alembic commands ###
